name: 'Deploy Action'
description: >-
  This is a example to update a git commit status.
  You need run another probot to watch this status event.
inputs:
  # Hacked way in this action.
  auth_token:
    description: 'Auth token used to API. Hacked way to get github.token'
    required: true
    default: "${{ github.token }}"
  pull_sha:
    description: 'Commit SHA'
    default: "${{ github.event.pull_request.head.sha }}"
    required: false

  # You might want to use this.
  deploy_to:
    description: 'Target cluster/environment'
    default: 'dev'
    required: true
  sha_length:
    description: 'SHA will short to N'
    default: '10'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
