name: 'Update Status'
description: 'Update status'
inputs:
  # Hacked way in this action.
  auth_token:
    description: 'Auth token used to API'
    required: true
    default: "${{ github.token }}"
  pull_sha:
    description: 'Commit SHA'
    default: "${{ github.event.pull_request.head.sha }}"
    required: false

  # You might want to use this.
  state:
    description: 'Option: success, failure'
    required: false
    default: 'success'
  context:
    description: 'Over 40 characters will be cut.'
    required: false
    default: 'swaglive/action@update-status'
runs:
  using: 'docker'
  image: 'Dockerfile'
