name: Run flexible-env
on:
  push:
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        uses: ./flexible-env
      - run: echo ${{ env.FLEX_GIT_SHA }}
      - run: echo ${{ env.FLEX_GIT_REF }}