name: Test flexible-env
on:
  push:
    paths:
      - "flexible-env/**"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: docker build flexible-env 