name: Test kubectl-apply
on:
  push:
    paths:
      - "kubectl-apply/**"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: docker build kubectl-apply
